### PR TITLE
picasso text-color use contrastColor

### PR DESCRIPTION
**Pull request by pmattmann**
Picasso Activity Text-Color use contrastColor (depending on Category-Color)

image

### CODE REVIEW

**Review by carlobeltrame — COMMENTED** [review]
Maybe if we do this often, we could add two css classes and createa js function which just outputs the correct one of these two classes..?

**Review by usu — APPROVED** [review]
Do you dare to also implement this in the 2 prints? 😄

**Review by carlobeltrame — APPROVED** [review]

**Comment by pmattmann** [comment]
> Do you dare to also implement this in the 2 prints? 😄

ja.... chame natürli mache...

## Nuxt
image
image

## React
image
image

**Review by usu — APPROVED** [review]
Nice 🥇

**Pull request merged**
