### PR TITLE
Frontent remove snapshot tests in ApiSelect

### PR DESCRIPTION
**Pull request by BacLuc**

### CODE REVIEW

**Review by carlobeltrame — COMMENTED** [review]
Can you help me what the difference of this PR to #995 is, and what the motivation behind removing the snapshot test is?

**Comment by BacLuc** [comment]
> 
> 
> Can you help me what the difference of this PR to #995 is, and what the motivation behind removing the snapshot test is?

This is one additional commit to #995 that we as a team have the possibility to accept #995 without removing the snapshot test.
From the commit message:

We already have snapshot tests for ESelect and tests
for the ApiWrapper, so these snapshot's don't add much value.

**Review by carlobeltrame — APPROVED** [review]
I agree to remove this snapshot. Would the same apply to ApiTextField.spec.js.snap?

**Comment by BacLuc** [comment]
> I agree to remove this snapshot. Would the same apply to ApiTextField.spec.js.snap?

Yes, i will remove that too when i touch the test.

**Review by pmattmann — APPROVED** [review]

**Pull request merged**
