### PR TITLE
Chore/production performance

### PR DESCRIPTION
**Pull request by usu**
- adds some default resource values for production environment (the most important ones also configurable via env vars) (copied from https://github.com/ecamp/ecamp3/pull/3192)
- remove alpha references

@BacLuc any good idea how I can test this without pushing directly to stage?

### CODE REVIEW

**Comment by BacLuc** [comment]
> @BacLuc any good idea how I can test this without pushing directly to stage?

No, maybe we need a fourth Environment to Test GitHub actions.

I am trying to decouple the workflows from the workflows from ecamp, that you can Test Them in your fork.
But this will Take a while

**Review by carlobeltrame — APPROVED** [review]
Did you set any of the environment variables yet?

**Comment by usu** [comment]
> Did you set any of the environment variables yet?

I've set the following ones on staging to test if it properly injects them:
```
BROWSERLESS_MAXCONCURRENTSESSIONS = 2
BROWSERLESS_MAXQUEUELENGTH = 3
```

The idea is, that this runs through with okish default values. And then we can later fine-tune prod vs. staging in the variables based on usage and based on prometheus data.

**Review by BacLuc — APPROVED** [review]
I tested it with https://github.com/ecamp/ecamp3/actions/runs/4282767257/jobs/7458168679
on branch https://github.com/ecamp/ecamp3/tree/test-deployment-workflows

Ran into the permission problem with postgres again and had issues with newlines in the domain env variable.
That's why i needed so many runs.

**Comment by carlobeltrame** [comment]
> Ran into the permission problem with postgres again

Did you happen to find out how to solve it then? I'd like to document this so future setups can be easier

**Comment by BacLuc** [comment]
> > Ran into the permission problem with postgres again
> 
> Did you happen to find out how to solve it then? I'd like to document this so future setups can be easier

Yes, i documented my solution: https://github.com/ecamp/ecamp3/wiki/Deployment-installation-Kubernetes#setting-up-the-database
If it is the best one i don't know. But there is at least one.

**Comment by usu** [comment]
> > Did you set any of the environment variables yet?
> 
> I've set the following ones on staging to test if it properly injects them:
> 
> ```
> BROWSERLESS_MAXCONCURRENTSESSIONS = 2
> BROWSERLESS_MAXQUEUELENGTH = 3
> ```
> 
> The idea is, that this runs through with okish default values. And then we can later fine-tune prod vs. staging in the variables based on usage and based on prometheus data.

Seems to work as intended. Staging is deployed and running. And the 2 environment variables set above have successfully been forwarded to the pod.

image

**Pull request merged**
