### PR TITLE
Add Dev Data

### PR DESCRIPTION
**Pull request by DeNic0la**
**Requirements from #3574**

- [x] 5 or more collaborators
- [x] A camp where Bi-Pi is a manager, a camp where he is a member and a camp where he is a guest
- [x] Day responsibles (but not on all days)
- [x] Conditional camp fields (organizer, coach name etc.)
- [x] More categories than fit on one row on a portrait mode picasso
- [x] Some dark and light color categories
- [x] Categories using different numbering schemes, but still enough schedule entries per day to get to two-digit numbers (e.g. 2.12)
- [x] Schedule entries which go across a day boundary / are 24 hours or longer
- [x] Schedule entries with and without location and activity responsibles (some single, some multiple, some all)
- [x] Progress labels on most activities
- [x] Most activities with the default category layouts from our camp templates
- [x] Some activities with customized layouts
- [x] Long storyboard sections (in the order of 0.5-2 A4 pages long)
- [x] Using multiple newlines in a row to create spacing in a storyboard section
- [x] Enumeration lists which start at numbers other than 1., and go to numbers higher than 9.
- [ ] Nested enumeration lists and bullet lists
- [x] Times where 3 or more schedule entries overlap at the same time
- [ ] Occasional emoji in activity titles and contents

### CODE REVIEW

**Comment by DeNic0la** [comment]
As far as I can tell every requirement is met at least once. The last 3 requirements are just met once and I am not sure if that's enough. I documented the Dev-Data and will move that to the Wiki after this is on devel.

**Review by usu — APPROVED** [review]
PR looks good for me, thanks. 

2 related questions, we might want to discuss in the core team:
- all/most dev data is in German at the moment. Do we have any intention to have data also in English? Or not priority at the moment?
- do we believe we have any copyright problems by using Harry Potter and Star Wars reference? Or would this anyway fall into "fair use"?

**Comment by DeNic0la** [comment]
> - do we believe we have any copyright problems by using Harry Potter and Star Wars reference? Or would this anyway fall into "fair use"?


I was thinking about this. I did not create the Harry Potter Camp, AFAIK fanfiction is accepted/encouraged by the Author. Since Disney doesn't share that Mindset in courts i did not mention characters and by changing the name that camp would just become a story in space.

**Review by BacLuc — APPROVED** [review]
thx

**Pull request merged**
