### PR TITLE
Deploy alpha (test fast-forward worklow)

### PR DESCRIPTION
**Pull request by usu**

### CODE REVIEW

**Comment by usu** [comment]
> /fast-forward

Hmm, https://github.com/ecamp/ecamp3/actions/runs/3254469934/jobs/5342760618 says "This job was skipped", which would mean something in the if-clause already failed. @BacLuc any idea what failed?

**Comment by usu** [comment]
> Failed! Cannot do fast forward!

Nice, now it does what it should do:
https://github.com/ecamp/ecamp3/actions/runs/3258333752/jobs/5350337002
> RequestError [HttpError]: At least 1 approving review is required by reviewers with write access. You're not authorized to push to this branch.

**Review by carlobeltrame — APPROVED** [review]

**Comment by carlobeltrame** [comment]
Something still isn't right:
> RequestError [HttpError]: You're not authorized to push to this branch.

**Comment by carlobeltrame** [comment]
I tried adjusting the branch protection rules to allow the ecamp3 core team to push to this branch, but it doesn't work because we pass `GITHUB_TOKEN` to the workflow. This token represents a user which is not selectable in the branch protection rule exceptions [[1]](https://github.com/community/community/discussions/13836), and if it were that would apparently be a security hole. We could instead create a service token for @ecampcore and pass that to the action.

**Review by BacLuc — APPROVED** [review]

**Comment by carlobeltrame** [comment]
When I query the API myself using a new personal API token on my account, I get `"mergeable_state": "unstable"`, which would be fine (we should actually allow that, because it [indicates](https://github.com/octokit/octokit.net/issues/1763) that only non-required status checks such as Coveralls failed). That also matches with what the GitHub UI displays to me.
I don't understand why this workflow says it's "blocked"...

**Pull request closed without merging**
