### PR TITLE
dev-data: add 'J+S Kurs' camp prototype

### PR DESCRIPTION
**Pull request by BacLuc**

### CODE REVIEW

**Comment by pmattmann** [comment]
- [ ] All program sections have 3 entries. Is this intentional? 
- [ ] Abbreviation of "LS-T erleben" is P - I would suggest LS
- [ ] SafetyConsiderations are sometimes above / sometimes below. I would do the same consistently.

**Review by usu — APPROVED** [review]
Looks good to me.
When creating a new camp, I noticed that the newly added contentTypes are not shown in the preview. But that could be a separate issue/PR.

image

**Comment by BacLuc** [comment]
> Looks good to me. When creating a new camp, I noticed that the newly added contentTypes are not shown in the preview. But that could be a separate issue/PR.
> 
> image

i assume these are left over preferred content types

**Comment by BacLuc** [comment]
> * [x]  All program sections have 3 entries. Is this intentional?
done
> * [x]  Abbreviation of "LS-T erleben" is P - I would suggest LS
i used E for 'Erleben'... the what is the difficult part and that there is no confusion with lagersport
> * [x]  SafetyConsiderations are sometimes above / sometimes below. I would do the same consistently.
done

**Review by pmattmann — APPROVED** [review]

**Pull request merged**
