### PR TITLE
Improve compatibility with password managers

### PR DESCRIPTION
**Pull request by carlobeltrame**
Following the recommendations from:
https://hidde.blog/making-password-managers-play-ball-with-your-login-form/
https://developer.1password.com/docs/web/compatible-website-design/
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill

and some manual testing using 1password on desktop.

I will deploy this and check it on the phone, because that's where I had more issues previously (with 1password for Android).
It'd be great if you could help out by testing with your own password managers on all your devices :)

### CODE REVIEW

**Comment by carlobeltrame** [comment]
Proposing a new password on the register page does not work yet on my 1password on Android.

**Comment by manuelmeister** [comment]
It works on my iPhone

**Comment by carlobeltrame** [comment]
Looks like 1password on Android simply does not support generating new passwords directly in the browser. You always have to go to the app. https://support.1password.com/android-autofill/#save-or-create-a-new-login

@manuelmeister I don't have anything else open here. Please leave a review :) thanks

**Review by manuelmeister — APPROVED** [review]
LGTM

**Review by usu — APPROVED** [review]

**Pull request merged**
