### PR TITLE
api/README.md: add config needed for debugging

### PR DESCRIPTION
**Pull request by BacLuc**

### CODE REVIEW

**Review by usu — COMMENTED** [review]
- I normally use `XDEBUG_MODE="develop,trace,debug"`
Trace is probably an overkill though and I could disable it. Maybe similar for coverage?

- The idekey for VSCode is `VSCODE`. Could we add this as well?

- Restarting the containers with `docker-compose down` and `docker-compose up` is necessary

- Should we distribute a default .env file? (related to discussion at #2570)

**Comment by BacLuc** [comment]
> 

Also added the config for vscode.
Did not add a default .env file.

**Review by usu — APPROVED** [review]

**Review by carlobeltrame — APPROVED** [review]
Lgtm. Funnily enough, I don't have a .env file and I can still debug, and I don't really know why. But better to document it like this.

**Comment by BacLuc** [comment]
> Lgtm. Funnily enough, I don't have a .env file and I can still debug, and I don't really know why. But better to document it like this.

Also for incoming requests or when you run the tests?

**Pull request merged**
