### PR TITLE
PrintDataController Entpoint draft

### PR DESCRIPTION
**Pull request by pmattmann**
Explicit EndPoint to load all required Data for print in ONE Request.
Motivation: Make print a lot faster; reduce server-request loads.

The Group 'print' allows to control what information should be included.

On my Dev-Environment the HarryPotter-Camp loading all data takes 1.3seconds
On PR-Deplayment the HarryPotter-Camp loading all data takes half a seconds

Check out the response:
https://pr3612.ecamp3.ch/api/print/camp/05ce4b9836e9

### CODE REVIEW

**Comment by carlobeltrame** [comment]
If I understand correctly, we would need to adapt hal-json-vuex to be able to handle this response format, right? Could you instead output a fully HAL-compliant response?
And could we have this documented in the OpenAPI Swagger Docs? (This needs to be done manually if you write a plain controller manually, which is why it is [discouraged](https://api-platform.com/docs/core/controllers/) by API Platform)

**Comment by pmattmann** [comment]
## Core Meeting Dicision
- Pseudo-Entität 'CampPrintData' mit DTO analog zu Invitation
- Print Data-Load umbauen, nur diesen Endpoint laden

**Comment by manuelmeister** [comment]
This would probably need a test if we want to merge this, to notice when it breaks.

**Comment by BacLuc** [comment]
Not needed right now

**Pull request closed without merging**
