### PR TITLE
fix unittest

### PR DESCRIPTION
**Pull request by pmattmann**

### CODE REVIEW

**Review by BacLuc — APPROVED** [review]
Had the same idea: https://github.com/ecamp/ecamp3/commit/d65be3df28893d6d6ab37501b1e8ffccc1a1ca97

**Review by manuelmeister — APPROVED** [review]

**Comment by manuelmeister** [comment]
Sadly this did not work in the devel :(

**Comment by usu** [comment]
Strange, that the tests didn't fail before...
Thanks for fixing

**Comment by carlobeltrame** [comment]
Maybe renovate does not rebase / recreate its branches if there are no conflicts..? That could explain it I think

**Comment by BacLuc** [comment]
Just to backup what i tracked down:
UpdatePeriodTest: fix test

Since https://github.com/ecamp/ecamp3/commit/05edfbfb4eb2a5dfbd82222c33ec56e29f78dba5, the builds keep failing with this changed behaviour.
I tracked the behaviour to this line:
https://github.com/symfony/serializer/blob/76b9a43c4295ced6d5f43208ba858325d8f61f30/Normalizer/DateTimeNormalizer.php#L101

But we updated php already in https://github.com/ecamp/ecamp3/commit/f45c5fe1b9d327e9eb940c3fb5902d040e378b21.
???

**Pull request merged**
