### PR TITLE
Create new dev data camps #3574

### LINKED ISSUE #3574: Create new dev data camps
Many features have been added since we last added dev data camps. To make sure we develop and test with realistic data, some new camps should be added, including:

- 5 or more collaborators
- A camp where Bi-Pi is a manager, a camp where he is a member and a camp where he is a guest
- Day responsibles (but not on all days)
- Conditional camp fields (organizer, coach name etc.)
- More categories than fit on one row on a portrait mode picasso
- Some dark and light color categories
- Categories using different numbering schemes, but still enough schedule entries per day to get to two-digit numbers (e.g. 2.12)
- Schedule entries which go across a day boundary / are 24 hours or longer
- Times where 3 or more schedule entries overlap at the same time
- Schedule entries with and without location and activity responsibles (some single, some multiple, some all)
- Progress labels on most activities
- Most activities with the default category layouts from our camp templates
- Some activities with customized layouts
- Occasional emoji in activity titles and contents
- Long storyboard sections (in the order of 0.5-2 A4 pages long)
- Using multiple newlines in a row to create spacing in a storyboard section
- Nested enumeration lists and bullet lists
- Enumeration lists which start at numbers other than 1., and go to numbers higher than 9.
- Some links in some of the rich text fields
- ...

### PR DESCRIPTION
**Pull request by DeNic0la**
Fixes #3574

- [x] 5 or more collaborators
- [ ] A camp where Bi-Pi is a manager, a camp where he is a member and a camp where he is a guest
- [ ] Day responsibles (but not on all days)
- [ ] Conditional camp fields (organizer, coach name etc.)
- [ ] More categories than fit on one row on a portrait mode picasso
- [ ] Some dark and light color categories
- [ ] Categories using different numbering schemes, but still enough schedule entries per day to get to two-digit numbers (e.g. 2.12)
- [ ] Schedule entries which go across a day boundary / are 24 hours or longer
- [ ] Times where 3 or more schedule entries overlap at the same time
- [ ] Schedule entries with and without location and activity responsibles (some single, some multiple, some all)
- [ ] Progress labels on most activities
- [ ] Most activities with the default category layouts from our camp templates
- [ ] Some activities with customized layouts
- [ ] Occasional emoji in activity titles and contents
- [ ] Long storyboard sections (in the order of 0.5-2 A4 pages long)
- [ ] Using multiple newlines in a row to create spacing in a storyboard section
- [ ] Nested enumeration lists and bullet lists
- [ ] Enumeration lists which start at numbers other than 1., and go to numbers higher than 9.

### CODE REVIEW

**Comment by BacLuc** [comment]
Sorry, we had more or less the same idea: #3701

**Comment by carlobeltrame** [comment]
Can we close this? I think the changes in here were incorporated into #3701, correct?

**Comment by DeNic0la** [comment]
> Can we close this? I think the changes in here were incorporated into #3701, correct?

Yes, the implemented changes were incorporated. However the #3574 has a long list of specific requirements. Most of those are not done (or at least not by me or @BacLuc the last time i checked). 

The Question is are the Requirements in #3574 required or is the current state sufficient? 

I am kinda overwhelmed with school at the moment so GitHub issues are on ice. I would pick them back up if they are still relevant by then but feel free to close or reassign my things for now.

**Comment by carlobeltrame** [comment]
Alright, no problem :) the remaining points in #3574 are still planned to be implemented. We merged #3701 because it was already a big improvement over the previous state. Given that this PR now obviously has merge conflicts, I assume it would be easier to start fresh from devel in case you want to continue on #3574, so I'm closing this for now so we are aware of what is being worked on and what isn't. Feel free to open a new PR in case you have anything new :)

**Pull request closed without merging**
