### PR TITLE
Reduce number of JOINs in FilterByCampCollaboration and FiltersByContentNode

### PR DESCRIPTION
**Pull request by pmattmann**
This PR reduces the number of JOINs for FilterByCampCollaboration and FiltersByContentNode.

### CODE REVIEW

**Comment by BacLuc** [comment]
I looked at the query plan against prod data, and your change does the following for big query when you hit
http://localhost:3000/api/activities?camp=%2Fapi%2Fcamps%2F$CAMP_ID

image

image

On the first glance it seems to make sense, but in the end the effect seems minimal.
What did you want to optimize?

Precomputing the camps of the users with a WITH does not help too, because the query optimizer already does this.

**Comment by BacLuc** [comment]
Related to #4536

**Comment by usu** [comment]
@pmattmann I guess this is superseded by #5000 and can be closed, right?

**Comment by pmattmann** [comment]
> @pmattmann I guess this is superseded by #5000 and can be closed, right?

yes

**Pull request closed without merging**
